// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenMind.Customer.Integration.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Customer created event
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class CustomerCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""CustomerCreated"",""doc"":""Customer created event"",""namespace"":""OpenMind.Customer.Integration.Events"",""fields"":[{""name"":""Id"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""FirstName"",""type"":""string""},{""name"":""LastName"",""type"":""string""},{""name"":""PhoneNumber"",""type"":""string""},{""name"":""Address"",""type"":""string""},{""name"":""BillingAddress"",""type"":""string""},{""name"":""Email"",""type"":""string""},{""name"":""CreatedAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		private System.Guid _Id;
		private string _FirstName;
		private string _LastName;
		private string _PhoneNumber;
		private string _Address;
		private string _BillingAddress;
		private string _Email;
		private System.DateTime _CreatedAt;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CustomerCreated._SCHEMA;
			}
		}
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				this._FirstName = value;
			}
		}
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				this._LastName = value;
			}
		}
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				this._PhoneNumber = value;
			}
		}
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this._Address = value;
			}
		}
		public string BillingAddress
		{
			get
			{
				return this._BillingAddress;
			}
			set
			{
				this._BillingAddress = value;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.FirstName;
			case 2: return this.LastName;
			case 3: return this.PhoneNumber;
			case 4: return this.Address;
			case 5: return this.BillingAddress;
			case 6: return this.Email;
			case 7: return this.CreatedAt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Guid)fieldValue; break;
			case 1: this.FirstName = (System.String)fieldValue; break;
			case 2: this.LastName = (System.String)fieldValue; break;
			case 3: this.PhoneNumber = (System.String)fieldValue; break;
			case 4: this.Address = (System.String)fieldValue; break;
			case 5: this.BillingAddress = (System.String)fieldValue; break;
			case 6: this.Email = (System.String)fieldValue; break;
			case 7: this.CreatedAt = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
