// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenMind.Customer.Integration.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Customer deleted event
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class CustomerDeleted : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""CustomerDeleted"",""doc"":""Customer deleted event"",""namespace"":""OpenMind.Customer.Integration.Events"",""fields"":[{""name"":""Id"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""DeletedAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		private System.Guid _Id;
		private System.DateTime _DeletedAt;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return CustomerDeleted._SCHEMA;
			}
		}
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public System.DateTime DeletedAt
		{
			get
			{
				return this._DeletedAt;
			}
			set
			{
				this._DeletedAt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.DeletedAt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Guid)fieldValue; break;
			case 1: this.DeletedAt = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
